[package]
name = "arcball"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
readme = "README.md"
keywords = ["camera", "arcball", "shoemake"]
license = "MIT"
exclude = [
	".travis.yml",
	".gitignore",
]
description = "An implementation of the Shoemake Arcball camera"
documentation = ""
homepage = ""
repository = ""

[dependencies]
cgmath = "0.12.0"

[dev-dependencies]
glium = "0.16.0"

