[package]
name = "arcball"
version = "0.2.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
readme = "README.md"
keywords = ["camera", "arcball", "shoemake"]
license = "MIT"
exclude = [
	".travis.yml",
	".gitignore",
]
description = "An implementation of the Shoemake Arcball camera"
documentation = "http://www.willusher.io/arcball/arcball/"
homepage = "https://github.com/Twinklebear/arcball"
repository = "https://github.com/Twinklebear/arcball"

[dependencies]
cgmath = "0.14.0"
clippy = { version = "0.0.129", optional = true }

[dev-dependencies]
glium = "0.16.0"

[features]
unstable = ["clippy"]

